/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Validations.validations;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Class.user.SetOfUsers;
import Class.user.User;
import Class.Serialization.Serialization;

/**
 *
 * @author Uthpala Jayawardena
 */
public class Register extends javax.swing.JFrame {
  
    private static SetOfUsers theUsers = new SetOfUsers();

    private static final String FILE_NAME_Users = "DataFiles/Users.txt";
    
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        try {
            for (User member : Serialization.deserializeUsers()) {
                theUsers.addUser(member);
                member.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFName = new javax.swing.JLabel();
        jLabelLName = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jLabelMNumber = new javax.swing.JLabel();
        mobile = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jLabelCPassword = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonSignup = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        password1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1005, 555));
        getContentPane().setLayout(null);

        jLabelFName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFName.setText("First Name");
        getContentPane().add(jLabelFName);
        jLabelFName.setBounds(322, 129, 100, 17);

        jLabelLName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLName.setText("Last Name");
        getContentPane().add(jLabelLName);
        jLabelLName.setBounds(322, 177, 100, 17);

        jLabelCity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCity.setText("City");
        getContentPane().add(jLabelCity);
        jLabelCity.setBounds(322, 229, 70, 17);

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelEmail.setText("Email");
        getContentPane().add(jLabelEmail);
        jLabelEmail.setBounds(322, 277, 70, 17);
        getContentPane().add(firstName);
        firstName.setBounds(525, 129, 195, 30);

        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        getContentPane().add(lastName);
        lastName.setBounds(525, 177, 195, 30);
        getContentPane().add(city);
        city.setBounds(525, 229, 195, 30);
        getContentPane().add(email);
        email.setBounds(525, 277, 195, 30);

        jLabelMNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMNumber.setText("Mobile Number");
        getContentPane().add(jLabelMNumber);
        jLabelMNumber.setBounds(322, 324, 130, 17);
        getContentPane().add(mobile);
        mobile.setBounds(525, 324, 195, 30);

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPassword.setText("Password");
        getContentPane().add(jLabelPassword);
        jLabelPassword.setBounds(322, 370, 100, 17);

        jLabelCPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelCPassword.setText("Confirm Password");
        getContentPane().add(jLabelCPassword);
        jLabelCPassword.setBounds(322, 418, 140, 17);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Registration");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(350, 29, 224, 47);

        jButtonSignup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSignup.setText("SignUp");
        jButtonSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSignupMouseClicked(evt);
            }
        });
        jButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSignup);
        jButtonSignup.setBounds(525, 471, 81, 25);

        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonReset.setText("Reset");
        jButtonReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonResetMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonReset);
        jButtonReset.setBounds(649, 471, 71, 25);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Already a member ?");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 520, 190, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Login");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(660, 510, 60, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(880, 30, 89, 37);
        getContentPane().add(password);
        password.setBounds(525, 370, 195, 30);
        getContentPane().add(password1);
        password1.setBounds(525, 418, 195, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo-main.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 110, 1070, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    //signup button click
    private void jButtonSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSignupMouseClicked
        // TODO add your handling code here:
        String firstname, lastname, Address, City, Email, Mobile, Password, 
                Password1;
        if (firstName.getText().isEmpty() || lastName.getText().isEmpty() ||  
                city.getText().isEmpty()
                || email.getText().isEmpty() || mobile.getText().isEmpty() || 
                password.getText().isEmpty() || password1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Please provide all the details...", "Error", 
                    JOptionPane.ERROR_MESSAGE);

        } else {
            if (validations.isEmail(email.getText())) {
                firstname = firstName.getText();
                lastname = lastName.getText();
                City = city.getText();
                Email = email.getText();
                Mobile = mobile.getText();
                Password = password.getText();
                Password1 = password1.getText();

                if (Password.equals(Password1)) {
                    String status = registerUser(firstname, lastname, "user", 
                            City, Email, Mobile, Password);
                    if (status.equals("success")) {
                        JOptionPane.showMessageDialog(this, 
                                "You have registered successful", 
                                "Congradulations", 
                                JOptionPane.INFORMATION_MESSAGE);
                        clear();
                        try {
                            for (User user : Serialization.deserializeUsers()) {
                                user.print();

                            }
                        } catch (IOException | ClassNotFoundException ex) {
                            Logger.getLogger(Register.class.getName()).
                                    log(Level.SEVERE, null, ex);
                        }
                        Login l = new Login();
                        l.setVisible(true);
                        this.hide();

                    } else {
                        JOptionPane.showMessageDialog(this, 
                                "Registration unsuccessful...", "Error", 
                                JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, 
                           "Confirmation password must be same as the password", 
                            "Error", JOptionPane.ERROR_MESSAGE);

                }
            } else {
                JOptionPane.showMessageDialog(this, 
                        "Please provide a valied email address...", "Error", 
                        JOptionPane.ERROR_MESSAGE);

            }
        }
        

    }//GEN-LAST:event_jButtonSignupMouseClicked

    
      /**
     *
     * @param firstName
     * @param lastName
     * @param userLevel
     * @param city
     * @param email
     * @param mobile
     * @param password
     * @return status
     */
    //user registration
    public String registerUser(String firstName, String lastName, 
            String userLevel, String city, String email, String mobile, 
            String password) {
        String status = "";
        new User.SingletonBuilder(firstName, lastName, "user", email, mobile, 
                password).city(city).build();
        theUsers.addUser(User.getInstance());
        try {
            Serialization.Serialize(theUsers, FILE_NAME_Users);
            status = "success";
        } catch (Exception ex) {
            status = "fail";
            System.out.println(ex.getMessage());
        }

        return status;
    }
    
    
    private void jButtonResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonResetMouseClicked
        // TODO add your handling code here:
         clear();
         
    }//GEN-LAST:event_jButtonResetMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        
        Login l = new Login();
        l.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSignupActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login L = new Login();
        L.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton1ActionPerformed

    //clear method
     public void clear() {
        firstName.setText("");
        lastName.setText("");
        city.setText("");
        email.setText("");
        mobile.setText("");
        password.setText("");
        password1.setText("");

        theUsers.removeAll(theUsers);
        try {
            for (User user : Serialization.deserializeUsers()) {
                theUsers.addUser(user);
                user.print();
            }
        } catch (IOException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
     
     
     
     
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField city;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPassword;
    private javax.swing.JLabel jLabelCity;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFName;
    private javax.swing.JLabel jLabelLName;
    private javax.swing.JLabel jLabelMNumber;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField mobile;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField password1;
    // End of variables declaration//GEN-END:variables
}
